FROM gatsbyjs/gatsby:onbuild as build

#Copy the built website over
FROM nginx:1.19.7
EXPOSE 80

# Configure Nginx for http basic auth
COPY nginx/staging-nginx.conf /etc/nginx/nginx.conf
COPY nginx/http-basic-auth-start.sh /etc/nginx/http-basic-auth-start.sh

# Add website contents
COPY --from=build /app/public /usr/share/nginx/html

# Prevent web scrapers
RUN echo "User-agent: * Disallow: /" > /usr/share/nginx/html/robots.txt

CMD /etc/nginx/http-basic-auth-start.sh
