name: Contentful Publish
on:
  repository_dispatch:
    types: ["publish-event"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: dokku-rebuild
        uses: fifsky/ssh-action@master
        with:
          command: |
            dokku ps:rebuild website
          host: 'ssh://dokku@apple.pierobotics.org:22/website'
          user: dokku
          key: ${{ secrets.DOKKU_WEBSITE_KEY }}
