name: Code Publish
on:
  # TODO: Add for push/merge to master?
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ format('ssh://{0}@{1}:22/website', secrets.DOKKU_USER, secrets.DOKKU_SERVER) }}
          ssh_private_key: ${{ secrets.DOKKU_WEBSITE_KEY }}
